spring:
  application:
    name: demo
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token:
      scheme: http
      kv:
        enabled: true
        backend: secret
        default-context: application

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: ${username} # References the 'username' key from the Vault path
    password: ${password} # References the 'password' key from the Vault path